# Generated by Django 3.2.25 on 2024-04-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nome do Consumidor')),
                ('document', models.CharField(max_length=14, unique=True, verbose_name='Documento(CPF/CNPJ)')),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('city', models.CharField(max_length=128, verbose_name='Cidade')),
                ('state', models.CharField(max_length=128, verbose_name='Estado')),
                ('consumption', models.IntegerField(blank=True, null=True, verbose_name='Consumo(kWh)')),
                ('distributor_tax', models.FloatField(blank=True, null=True, verbose_name='Tarifa da Distribuidora')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial')], max_length=128, verbose_name='Tipo de Consumidor')),
                ('consumption_range', models.CharField(choices=[('0-100', '0-100'), ('101-200', '101-200'), ('201-300', '201-300'), ('301-400', '301-400'), ('401-500', '401-500'), ('501-600', '501-600'), ('601-700', '601-700'), ('701-800', '701-800'), ('801-900', '801-900'), ('901-1000', '901-1000')], max_length=128, verbose_name='Faixa de Consumo')),
                ('cover_value', models.FloatField(verbose_name='Valor da Cobertura')),
                ('discount_value', models.FloatField(verbose_name='Valor do Desconto')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.consumer')),
            ],
        ),
    ]
