# Generated by Django 3.2.25 on 2024-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='distributor_tax',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='discountrules',
            name='consumer_type',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], default='Residential', max_length=128, verbose_name='Tipo de Consumidor'),
        ),
        migrations.AlterField(
            model_name='discountrules',
            name='consumption_range',
            field=models.CharField(choices=[('0-10000', '0 a 10.000'), ('10000-20000', '10.000 a 20.000'), ('20000+', '20.000+')], default='0-10000', max_length=128, verbose_name='Faixa de Consumo'),
        ),
    ]
