# Generated by Django 3.2.25 on 2024-04-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20240406_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountrules',
            name='consumer_type',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], max_length=128, verbose_name='Tipo de Consumidor'),
        ),
        migrations.AlterField(
            model_name='discountrules',
            name='consumption_range',
            field=models.IntegerField(max_length=128, verbose_name='Faixa de Consumo'),
        ),
    ]
