# Generated by Django 3.2.25 on 2024-04-07 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_delete_discountrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_type', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], max_length=128, verbose_name='Tipo de Consumidor')),
                ('consumption_range', models.IntegerField(max_length=128, verbose_name='Faixa de Consumo')),
                ('cover_value', models.FloatField(verbose_name='Valor da Cobertura')),
                ('discount_value', models.FloatField(verbose_name='Valor do Desconto')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.consumer')),
            ],
        ),
    ]
