# Generated by Django 3.2.25 on 2024-04-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_discountrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountrules',
            name='cover_value',
            field=models.IntegerField(verbose_name='Valor da Cobertura'),
        ),
    ]
