# Generated by Django 3.2.25 on 2024-04-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_discountrules_cover_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrules',
            name='distributor_tax',
            field=models.FloatField(default=0.0, verbose_name='Tarifa da Distribuidora'),
        ),
        migrations.AlterField(
            model_name='discountrules',
            name='consumption_range',
            field=models.IntegerField(verbose_name='Faixa de Consumo'),
        ),
    ]
